name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - run: yarn
      - run: yarn lint

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - run: yarn
      - run: yarn test:unit

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - run: yarn
      - name: Setup Json-server
        run : npm install -g json-server
      - name: Run Json-server
        run: cd json-server && json-server --watch db.js --routes routes.json -p 8081 -q &
      - name: Cypress run
        uses: cypress-io/github-action@v2.2.7
        with:
          start: yarn serve
          wait-on: http://localhost:8080/
          record: true
        env:
          CYPRESS_baseUrl: http://localhost:8080/
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
